import fs from "node:fs";
import path from "node:path";
import SqlRiteCore from "../SqlRiteCore.js";

function generateTypes(options = { dir: "sql", output: "SqlRite.d.ts" }) {
	const dirs = Array.isArray(options.dir) ? options.dir : [options.dir];
	const existingDirs = dirs.filter((d) => fs.existsSync(d));

	if (existingDirs.length === 0) {
		console.warn(`No directories found to scan for SQL files. Expected: ${dirs.join(", ")}`);
		return;
	}

	const files = existingDirs.flatMap((d) => SqlRiteCore.getFiles(d));
	const chunks = SqlRiteCore.parseSql(files);

	let ts = `// Generated by SqlRite Codegen. Do not edit manually.

export interface SqlRiteOptions {
	path?: string;
	dir?: string | string[];
}

export interface SqlRiteResult {
	changes: number;
	lastInsertRowid: number | bigint;
}

export interface SqlRitePreparedStatements<T = any, P = Record<string, any>> {
	all: (params?: P) => Promise<T[]>;
	get: (params?: P) => Promise<T | undefined>;
	run: (params?: P) => Promise<SqlRiteResult>;
}

export interface SqlRiteSyncPreparedStatements<T = any, P = Record<string, any>> {
	all: (params?: P) => T[];
	get: (params?: P) => T | undefined;
	run: (params?: P) => SqlRiteResult;
}

export class SqlRiteSync {
	constructor(options?: SqlRiteOptions);
	close(): void;
`;

	for (const exec of chunks.EXEC) {
		ts += `	${exec.name}(params?: Record<string, any>): void;\n`;
	}

	for (const prep of chunks.PREP) {
		ts += `	${prep.name}: SqlRiteSyncPreparedStatements;\n`;
	}

	ts += `}\n\nexport default class SqlRite {\n`;
	ts += `	private constructor(options?: SqlRiteOptions, token?: symbol);\n`;
	ts += `	static open(options?: SqlRiteOptions): Promise<SqlRite>;\n`;
	ts += `	ready(): Promise<SqlRite>;\n`;
	ts += `	close(): Promise<void>;\n`;

	for (const exec of chunks.EXEC) {
		ts += `	${exec.name}(params?: Record<string, any>): Promise<void>;\n`;
	}

	for (const prep of chunks.PREP) {
		ts += `	${prep.name}: SqlRitePreparedStatements;\n`;
	}

	ts += `}\n`;

	fs.writeFileSync(options.output, ts);
	console.log(`Successfully generated types to ${options.output}`);
}

const args = process.argv.slice(2);
const dir = args[0] || "sql";
generateTypes({ dir, output: "SqlRite.d.ts" });
