import { existsSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import SqlRiteCore from "../SqlRiteCore.js";

// Static types for the "./sync" and "./core" package entries, emitted only with
// --base. All shipped .d.ts files are generated at prepack and removed at
// postpack: a d.ts sitting next to its .js sibling would shadow the JSDoc
// source during in-repo typechecking.
const SYNC_DTS = `// Generated by SqlRite Codegen. Do not edit manually.
export { SqlRiteSync as default } from "./SqlRite.js";
`;

const CORE_DTS = `// Generated by SqlRite Codegen. Do not edit manually.
import type { DatabaseSync, StatementSync } from "node:sqlite";
import type { SqlRiteOptions } from "./SqlRite.js";

export interface Chunk {
	type: string;
	name: string;
	sql: string;
	bigint?: boolean;
}

export interface Chunks {
	INIT: Chunk[];
	EXEC: Chunk[];
	TX: Chunk[];
	PREP: Chunk[];
	MIGRATE: Array<Chunk & { version: number }>;
}

export default class SqlRiteCore {
	static openDb(options: SqlRiteOptions & { path: string }): DatabaseSync;
	static initDb(db: DatabaseSync, options?: SqlRiteOptions): void;
	static applyMigrations(db: DatabaseSync, migrations: Array<Chunk & { version: number }>): void;
	static registerFunctions(db: DatabaseSync, functions?: string | string[]): Promise<void>;
	static loadChunks(options: SqlRiteOptions): Chunks;
	static getFiles(dir: string): string[];
	static parseSql(files: string[]): Chunks;
	static template(sql: string, params?: Record<string, unknown>, context?: string): string;
	static prepareMeta(db: DatabaseSync, bigint: boolean): StatementSync;
	static result(metaStmt: StatementSync): {
		changes: number | bigint;
		lastInsertRowid: number | bigint;
	};
	static jsonify(params?: Record<string, unknown> | null): Record<string, unknown>;
}
`;

function generateTypes({ dir = "sql", output = "SqlRite.d.ts", base = false }) {
	// --base emits only the static surface (the shipped package types); no .sql scan.
	let chunks = /** @type {import("../SqlRiteCore.js").Chunks} */ ({
		INIT: [],
		EXEC: [],
		TX: [],
		PREP: [],
		MIGRATE: [],
	});
	if (!base) {
		const dirs = Array.isArray(dir) ? dir : [dir];
		const existingDirs = dirs.filter((d) => existsSync(d));
		if (existingDirs.length === 0) {
			console.warn(`No directories found to scan for SQL files. Expected: ${dirs.join(", ")}`);
			return;
		}
		chunks = SqlRiteCore.parseSql(existingDirs.flatMap((d) => SqlRiteCore.getFiles(d)));
	}

	const lines = [
		"// Generated by SqlRite Codegen. Do not edit manually.",
		"",
		"export interface SqlRiteOptions {",
		"	path?: string;",
		"	dir?: string | string[];",
		"	functions?: string | string[];",
		"	params?: Record<string, string | number | boolean | null>;",
		"	readers?: number;",
		"	timeout?: number;",
		"	cacheSize?: number;",
		"	mmapSize?: number;",
		"	maxPageCount?: number;",
		"	[option: string]: unknown; // passthrough to node:sqlite DatabaseSync",
		"}",
		"",
		"export interface SqlRiteResult {",
		"	changes: number;",
		"	lastInsertRowid: number;",
		"}",
		"",
		"export interface SqlRiteBigIntResult {",
		"	changes: bigint;",
		"	lastInsertRowid: bigint;",
		"}",
		"",
		"export interface SqlRitePreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): Promise<T[]>;",
		"	get(params?: P): Promise<T | undefined>;",
		"	run(params?: P): Promise<SqlRiteResult>;",
		"}",
		"",
		"export interface SqlRiteBigIntPreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): Promise<T[]>;",
		"	get(params?: P): Promise<T | undefined>;",
		"	run(params?: P): Promise<SqlRiteBigIntResult>;",
		"}",
		"",
		"export interface SqlRiteSyncPreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): T[];",
		"	get(params?: P): T | undefined;",
		"	run(params?: P): SqlRiteResult;",
		"}",
		"",
		"export interface SqlRiteSyncBigIntPreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): T[];",
		"	get(params?: P): T | undefined;",
		"	run(params?: P): SqlRiteBigIntResult;",
		"}",
		"",
		"export class SqlRiteSync {",
		"	constructor(options?: SqlRiteOptions);",
		"	static open(options?: SqlRiteOptions): Promise<SqlRiteSync>;",
		"	close(): void;",
		"	[Symbol.dispose](): void;",
	];
	// The shipped base types stay loose on dynamic methods; generated types drop
	// the index signature so a typo'd method name is a type error.
	if (base) lines.push("	[method: string]: any;");

	for (const exec of chunks.EXEC) {
		const ret = exec.bigint ? "SqlRiteBigIntResult" : "SqlRiteResult";
		lines.push(`	${exec.name}(params?: Record<string, unknown>): ${ret};`);
	}
	for (const tx of chunks.TX) {
		const ret = tx.bigint ? "SqlRiteBigIntResult" : "SqlRiteResult";
		lines.push(`	${tx.name}(params?: Record<string, unknown>): ${ret};`);
	}
	for (const prep of chunks.PREP) {
		const iface = prep.bigint
			? "SqlRiteSyncBigIntPreparedStatements"
			: "SqlRiteSyncPreparedStatements";
		lines.push(`	${prep.name}: ${iface};`);
	}

	lines.push("}", "", "export default class SqlRite {");
	lines.push("	private constructor(options?: SqlRiteOptions, token?: symbol);");
	lines.push("	static open(options?: SqlRiteOptions): Promise<SqlRite>;");
	lines.push("	ready(): Promise<SqlRite>;");
	lines.push("	close(): Promise<void>;");
	lines.push("	[Symbol.asyncDispose](): Promise<void>;");
	if (base) lines.push("	[method: string]: any;");

	for (const exec of chunks.EXEC) {
		const ret = exec.bigint ? "SqlRiteBigIntResult" : "SqlRiteResult";
		lines.push(`	${exec.name}(params?: Record<string, unknown>): Promise<${ret}>;`);
	}
	for (const tx of chunks.TX) {
		const ret = tx.bigint ? "SqlRiteBigIntResult" : "SqlRiteResult";
		lines.push(`	${tx.name}(params?: Record<string, unknown>): Promise<${ret}>;`);
	}
	for (const prep of chunks.PREP) {
		const iface = prep.bigint ? "SqlRiteBigIntPreparedStatements" : "SqlRitePreparedStatements";
		lines.push(`	${prep.name}: ${iface};`);
	}

	lines.push("}", "");

	writeFileSync(output, lines.join("\n"));
	if (base) {
		writeFileSync("SqlRiteSync.d.ts", SYNC_DTS);
		writeFileSync("SqlRiteCore.d.ts", CORE_DTS);
	}
	console.log(`Generated ${output}`);
}

const { values, positionals } = parseArgs({
	options: { base: { type: "boolean", default: false } },
	allowPositionals: true,
});
generateTypes({ dir: positionals[0] ?? "sql", base: values.base });
