import fs from "node:fs";
import SqlRiteCore from "../SqlRiteCore.js";

function generateTypes(options = { dir: "sql", output: "SqlRite.d.ts" }) {
	const dirs = Array.isArray(options.dir) ? options.dir : [options.dir];
	const existingDirs = dirs.filter((d) => fs.existsSync(d));

	if (existingDirs.length === 0) {
		console.warn(`No directories found to scan for SQL files. Expected: ${dirs.join(", ")}`);
		return;
	}

	const files = existingDirs.flatMap((d) => SqlRiteCore.getFiles(d));
	const chunks = SqlRiteCore.parseSql(files);

	const lines = [
		"// Generated by SqlRite Codegen. Do not edit manually.",
		"",
		"export interface SqlRiteOptions {",
		"	path?: string;",
		"	dir?: string | string[];",
		"}",
		"",
		"export interface SqlRiteResult {",
		"	changes: number;",
		"	lastInsertRowid: number | bigint;",
		"}",
		"",
		"export interface SqlRitePreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): Promise<T[]>;",
		"	get(params?: P): Promise<T | undefined>;",
		"	run(params?: P): Promise<SqlRiteResult>;",
		"}",
		"",
		"export interface SqlRiteSyncPreparedStatements<T = Record<string, unknown>, P = Record<string, unknown>> {",
		"	all(params?: P): T[];",
		"	get(params?: P): T | undefined;",
		"	run(params?: P): SqlRiteResult;",
		"}",
		"",
		"export class SqlRiteSync {",
		"	constructor(options?: SqlRiteOptions);",
		"	close(): void;",
	];

	for (const exec of chunks.EXEC) {
		lines.push(`	${exec.name}(): void;`);
	}
	for (const prep of chunks.PREP) {
		lines.push(`	${prep.name}: SqlRiteSyncPreparedStatements;`);
	}

	lines.push("}", "", "export default class SqlRite {");
	lines.push("	private constructor(options?: SqlRiteOptions, token?: symbol);");
	lines.push("	static open(options?: SqlRiteOptions): Promise<SqlRite>;");
	lines.push("	ready(): Promise<SqlRite>;");
	lines.push("	close(): Promise<void>;");

	for (const exec of chunks.EXEC) {
		lines.push(`	${exec.name}(): Promise<void>;`);
	}
	for (const prep of chunks.PREP) {
		lines.push(`	${prep.name}: SqlRitePreparedStatements;`);
	}

	lines.push("}", "");

	fs.writeFileSync(options.output, lines.join("\n"));
	console.log(`Generated ${options.output}`);
}

const args = process.argv.slice(2);
const dir = args[0] || "sql";
generateTypes({ dir, output: "SqlRite.d.ts" });
